version: '3.8'
services:
  api:
    container_name: vdt-midterm-api
    build:
      context: ./
      dockerfile: Dockerfile.local
    ports:
      - '4000:4000'
    restart: always
    image: vdt-midterm-api:v1
    env_file:
      - ./.env.development
    networks:
      - app-network
    depends_on:
      - db
  db:
    container_name: vdt-midterm-db
    image: mongo:latest
    ports:
      - '27017:27017'
    volumes:
      - mongodb_data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongo_user
      MONGO_INITDB_ROOT_PASSWORD: mongo_password
    restart: always
    networks:
      - app-network
networks:
  app-network:
    external: true

volumes:
  mongodb_data:
