version: '3.8'
services:
  api:
    container_name: ${NAME_API}
    build:
      context: ./
      dockerfile: Dockerfile
      args:
        IMAGE_TAG: ${IMAGE_TAG:-1.0.0}
    ports:
      - '4000:4000'
    restart: always
    image: ${NAME_API}:${IMAGE_TAG}
    environment:
      - IMAGE_TAG=${IMAGE_TAG:-1.0.0}
      - NAME_API=${NAME_API}
    networks:
      - app-network

networks:
  app-network:
    external: true
