replicaCount: 3
image:
  repository: tuanquang1811/vdt-midterm-api
  tag: v1
  pullPolicy: IfNotPresent
service:
  name: vdt-api
  type: NodePort
  ports:
    http:
      port: 4000
      targetPort: 4000
      nodePort: 30003
  labels:
    app: vdt-api